import 'package:mx_merchant/src/models/payment/pos_data_model.dart';
import 'package:mx_merchant/src/models/payment/purchase_model.dart';
import 'package:mx_merchant/src/utils/enums.dart';

import '../bank/bank_account_model.dart';
import '../card/card_model.dart';
import '../customer/customer_model.dart';

/// This API can make payments, delete payments, and get information on created payments.
/// This API can be used by anyone who is interested in online payments.
/// This can be used by new businesses going into the online market or local businesses that want to move their business online.
class MxPaymentRequestModel {
  /// The payment amount. Must not be 0.
  final double amount;

  /// Type of transaction.
  final MxPaymentTransactionType? paymentType;

  final MxPaymentTenderType tenderType;

  /// Card Account Object. Required if tenderType is `MxPaymentTenderType.card`.
  final MxCardModel? cardAccount;

  /// Bank Account Object. Required if tenderType is `MxPaymentTenderType.check` or `MxPaymentTenderType.ach`.
  final MxBankAccountModel? bankAccount;

  /// Gets or sets the ACH entry class.
  final MxPaymentEntryClass? entryClass;

  /// Indicates that this payment should NOT be added to current batch.
  /// AuthOnly payment won't be settled.
  final bool? authOnly;

  /// Should this card be authorized?
  final bool? isAuth;

  /// Should this transaction be settled?
  final bool? isSettleFunds;

  /// Associate the payment to an existing customer in your customer database.
  final MxCustomerModel? customer;

  /// Customer Name. 256 char. Does NOT associate payment to customer.
  final String? customerName;

  /// Client provided customer reference number.
  /// Associates with Customer Number.
  /// Cannot be combined with invoiceId and clientReference if B2B is on.
  final String? customerCode;

  /// Memo field. Can include a stringified JSON object.
  final String? meta;

  /// A merchant-supplied identifier to uniquely identify a payment request
  /// to facilitate retries due to I/O related issues.
  /// This identifier must be unique.
  final int? replayId;

  final MxPaymentSource? source;

  /// Client provided payment reference number.
  /// Can be associated with multiple payments. 17 char max.
  final String? clientReference;

  /// Client provided invoice number.
  /// Generated by server if not provided. 16 char max.
  final String? invoice;

  /// Existing MX Merchant invoice ids.
  final List<String>? invoiceIds;

  /// Existing MX Merchant order ids.
  final List<String>? orderIds;

  /// Tax Amount. Included in amount.
  final double? tax;

  /// If true, tax amount must be 0.
  final bool? taxExempt;

  /// POS transaction data.
  final MxPosDataModel? posData;

  /// Gets/Sets the device identifier, this is the terminal id.
  final String? device;

  /// List of purchases. Used by level 3 data during settlement.
  final List<MxPurchaseModel>? purchases;

  /// Gets/Sets the ship amount, used by level 3 data during settlement.
  final double? shipAmount;

  /// Gets/Sets the 3-digit alphanumeric ship-to country code, e.g. USA.
  final String? shipToCountry;

  /// Gets/Sets the ship-to zip code, used by level 3 data during settlement.
  final String? shipToZip;

  /// Checks if the card is a business card. Only used when B2B is enabled.
  final bool? shouldGetCreditCardLevel;

  /// Use this param to vault a new card to a new or existing customer.
  final bool? shouldVaultCard;

  /// Gets/Sets the amount of the gratuity. Included in amount.
  final double? tip;

  /// Gets/Sets the VAT amount, used by level 3 data during settlement.
  final double? vatAmount;

  /// Gets/Sets the VAT rate, used by level 3 data during settlement.
  final double? vatRate;

  /// Associate a tag with the payment.
  /// You must set up the tag first in MX Merchant.
  final List<String>? tags;

  const MxPaymentRequestModel({
    required this.amount,
    required this.tenderType,
    this.paymentType = .sale,
    this.cardAccount,
    this.bankAccount,
    this.entryClass = .web,
    this.authOnly = false,
    this.isAuth = false,
    this.isSettleFunds = false,
    this.customer,
    this.customerName,
    this.customerCode,
    this.meta,
    this.replayId,
    this.source = .api,
    this.clientReference,
    this.invoice,
    this.invoiceIds,
    this.orderIds,
    this.tax,
    this.taxExempt = false,
    this.posData,
    this.device,
    this.purchases,
    this.shipAmount,
    this.shipToCountry,
    this.shipToZip,
    this.shouldGetCreditCardLevel,
    this.shouldVaultCard,
    this.tip,
    this.vatAmount,
    this.vatRate,
    this.tags,
  }) : assert(amount > 0, 'Amount must be greater than 0'),
       assert(tenderType != MxPaymentTenderType.card || cardAccount != null, 'cardAccount is required when tenderType is card'),
       assert(
         tenderType != MxPaymentTenderType.check && tenderType != MxPaymentTenderType.ach || bankAccount != null,
         'bankAccount is required when tenderType is check or ach',
       ),
       assert(clientReference == null || clientReference.length <= 17, 'clientReference must be 17 characters or fewer'),
       assert(invoice == null || invoice.length <= 16, 'invoice must be 16 characters or fewer'),
       assert(customerName == null || customerName.length <= 256, 'customerName must be 256 characters or fewer'),
       assert(shipToCountry == null || shipToCountry.length == 3, 'shipToCountry must be a 3-character country code'),
       assert(taxExempt != true || tax == null || tax == 0, 'tax must be 0 when taxExempt is true');

  Map<String, dynamic> toBodyJson() => {
    'amount': amount,
    'paymentType': paymentType?.name,
    'tenderType': tenderType.name,
    'cardAccount': cardAccount?.toJson(),
    'bankAccount': bankAccount?.toJson(),
    'entryClass': entryClass?.name,
    'authOnly': authOnly,
    'isAuth': isAuth,
    'isSettleFunds': isSettleFunds,
    'customer': customer?.toJson(),
    'customerName': customerName,
    'customerCode': customerCode,
    'meta': meta,
    'replayId': replayId,
    'source': source?.name,
    'clientReference': clientReference,
    'invoice': invoice,
    'invoiceIds': invoiceIds,
    'orderIds': orderIds,
    'tax': tax,
    'taxExempt': taxExempt,
    'posData': posData?.toJson(),
    'device': device,
    'purchases': purchases?.map((e) => e.toJson()).toList(),
    'shipAmount': shipAmount,
    'shipToCountry': shipToCountry,
    'shipToZip': shipToZip,
    'ShouldGetCreditCardLevel': shouldGetCreditCardLevel,
    'shouldVaultCard': shouldVaultCard,
    'tip': tip,
    'vatAmount': vatAmount,
    'vatRate': vatRate,
    'tags': tags,
  }..removeWhere((_, value) => value == null);

  Map<String, dynamic> toQueryJson() => {'echo': true, 'includeCustomerMatches': true};

  factory MxPaymentRequestModel.fromJson(Map<String, dynamic> json) {
    return MxPaymentRequestModel(
      amount: json['amount'] ?? 0,
      paymentType: json['paymentType'] != null ? MxPaymentTransactionType.values.firstWhere((e) => e.name == json['paymentType']) : null,
      tenderType: MxPaymentTenderType.values.firstWhere((e) => e.name == json['tenderType']),
      cardAccount: json['cardAccount'] != null ? MxCardModel.fromJson(json['cardAccount']) : null,
      bankAccount: json['bankAccount'] != null ? MxBankAccountModel.fromJson(json['bankAccount']) : null,
      entryClass: json['entryClass'] != null ? MxPaymentEntryClass.values.firstWhere((e) => e.name == json['entryClass']) : null,
      authOnly: json['authOnly'] != null ? bool.tryParse(json['authOnly'].toString()) : null,
      isAuth: json['isAuth'] != null ? bool.tryParse(json['isAuth'].toString()) : null,
      isSettleFunds: json['isSettleFunds'] != null ? bool.tryParse(json['isSettleFunds'].toString()) : null,
      customer: json['customer'] != null ? MxCustomerModel.fromJson(json['customer']) : null,
      customerName: json['customerName'],
      customerCode: json['customerCode'],
      meta: json['meta'],
      replayId: json['replayId'] != null ? int.tryParse(json['replayId'].toString()) : null,
      source: json['source'] != null ? MxPaymentSource.values.firstWhere((e) => e.name == json['source']) : null,
      clientReference: json['clientReference'],
      invoice: json['invoice'],
      invoiceIds: json['invoiceIds'] != null ? List<String>.from(json['invoiceIds']) : null,
      orderIds: json['orderIds'] != null ? List<String>.from(json['orderIds']) : null,
      tax: json['tax'] != null ? double.tryParse(json['tax'].toString()) : null,
      taxExempt: json['taxExempt'] != null ? bool.tryParse(json['taxExempt'].toString()) : null,
      posData: json['posData'] != null ? MxPosDataModel.fromJson(json['posData']) : null,
      device: json['device'],
      purchases: json['purchases'] != null ? MxPurchaseModel.fromJsonArray(json['purchases']) : null,
      shipAmount: json['shipAmount'] != null ? double.tryParse(json['shipAmount'].toString()) : null,
      shipToCountry: json['shipToCountry'],
      shipToZip: json['shipToZip'],
      shouldGetCreditCardLevel: json['shouldGetCreditCardLevel'] != null ? bool.tryParse(json['shouldGetCreditCardLevel'].toString()) : null,
      shouldVaultCard: json['shouldVaultCard'] != null ? bool.tryParse(json['shouldVaultCard'].toString()) : null,
      tip: json['tip'] != null ? double.tryParse(json['tip'].toString()) : null,
      vatAmount: json['vatAmount'] != null ? double.tryParse(json['vatAmount'].toString()) : null,
      vatRate: json['vatRate'] != null ? double.tryParse(json['vatRate'].toString()) : null,
      tags: json['tags'] != null ? List<String>.from(json['tags']) : null,
    );
  }
}
