import '../../../utils/enums.dart';
import 'custom_field_option_model.dart';

class MxCreateCustomFieldRequestModel {
  /// Id for the custom field (Auto-generated by server)
  final String? id;

  /// Descriptor name for the custom field
  final String? name;

  /// Name for the custom field object
  final String? fieldName;

  /// Type of field.
  final MxCustomFieldDataType? fieldDataType;

  /// Always customer
  final String fieldSourceType;

  /// System level field (Default False)
  final bool isDeleted;

  /// System Level Field (Default False)
  final bool isSystem;

  /// Noting if the custom field is required to fill out
  final bool isRequired;

  /// Only required for Boolean and List. Name and Value should match.
  final List<MxCustomFieldOptionModel>? options;

  /// If you would like to get the response object, you should supply `echo = true` as a URL parameter.
  /// This is useful as it keeps the user from having to use a GET call to see the response object information.
  final bool echo;

  MxCreateCustomFieldRequestModel({
    this.id,
    this.name,
    this.fieldName,
    this.fieldDataType,
    this.fieldSourceType = 'Customer',
    this.isDeleted = false,
    this.isSystem = false,
    this.isRequired = false,
    this.options,
    this.echo = true,
  });

  Map<String, dynamic> toBodyJson() {
    return {
      'id': id,
      'name': name,
      'fieldName': fieldName,
      'fieldDataType': fieldDataType?.name,
      'fieldSourceType': fieldSourceType,
      'isDeleted': isDeleted,
      'isSystem': isSystem,
      'isRequired': isRequired,
      'options': options?.map((e) => e.toJson()).toList(),
    }..removeWhere((_, v) => v == null);
  }

  Map<String, dynamic> toQueryJson() {
    return {'echo': echo};
  }
}
